// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuxvabqnulwzcjrckjnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eHZhYnFudWx3emNqcmNram50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDEyMTksImV4cCI6MjA4ODcxNzIxOX0.YVfarDxHQhCvih01gJIA6KX4742T0xyGjVIWybXJZ-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    detectSessionInUrl: true,
    persistSession: true,
    autoRefreshToken: true,
  }
});